version: "3.8"
services:
  db_mongodb:
    image: 'mongo'
    volumes:
      - db_volume:/data/db
    env_file:
      - ./env/mongo.env
    networks:
      - db_net
  backend:
    build: ./backend
    ports:
      - '80:80'
    networks:
      - db_net
      - frontend_net
    volumes:
      - backend_logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - db_mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
      - frontend_net
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

networks:
  db_net:
  frontend_net:

volumes:
  db_volume:
  backend_logs:
