apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: tasks
        image: chrispiloten/kub-demo-tasks:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
